---

- name: Restart Mosquitto
  ansible.builtin.service:
    name: mosquitto
    state: restarted

- name: Reload systemd and restart Mosquitto
  ansible.builtin.systemd:
    daemon_reload: yes
  notify:
    - Restart Mosquitto
