---
- name: Restart Mosquitto
  ansible.builtin.service:
    name: mosquitto
    state: restarted

- name: Reload systemd and restart Mosquitto
  ansible.builtin.systemd:
    daemon_reload: true
  notify:
    - Restart Mosquitto

- name: Enable and start Mosquitto service
  ansible.builtin.service:
    name: mosquitto
    state: started
    enabled: true
